/**
 * Generates Svelte 5 icon components from `src/lib/icons/raw/*.svg`.
 * Run via `pnpm icons:generate` (also runs before `pnpm build`).
 */
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { basename, dirname, extname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), `..`);
const rawDir = join(root, `src/lib/icons/raw`);
const outDir = join(root, `src/lib/icons/generated`);

function toPascalCase(slug: string): string {
	return slug
		.split(/[^a-zA-Z0-9]+/)
		.filter(Boolean)
		.map((p) => p.charAt(0).toUpperCase() + p.slice(1).toLowerCase())
		.join(``);
}

function wrapSvg(svg: string): string {
	const inner = svg
		.trim()
		.replace(/^<svg\s/, `<svg class={classes} {...rest} `);
	return `<!-- generated by scripts/generate-icons.ts — do not edit -->
<script lang="ts">
	import type { SVGAttributes } from 'svelte/elements';

	let { class: classes = \`\`, ...rest }: SVGAttributes<SVGSVGElement> = $props();
</script>
${inner}
`;
}

mkdirSync(outDir, { recursive: true });
const files = readdirSync(rawDir).filter((f) => extname(f) === `.svg`);
if (files.length === 0) {
	console.warn(`No SVGs in ${rawDir}`);
	process.exit(0);
}

for (const file of files) {
	const slug = basename(file, `.svg`);
	const componentName = `${toPascalCase(slug)}Icon`;
	const svg = readFileSync(join(rawDir, file), `utf8`);
	writeFileSync(join(outDir, `${componentName}.svelte`), wrapSvg(svg), `utf8`);
	console.log(`Wrote ${componentName}.svelte`);
}
